// app/layout.js

import React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { StateContext } from "../context/StateContext"
import { Navbar, Footer } from "../components"
import { Toaster } from "react-hot-toast"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Breinoptimaal",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StateContext>
      <html lang="en">
        <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
        </head>
        <body className={inter.className}>
        <Navbar />
          <div className="layout">
            <Toaster />
            <main className="main-container">{children}</main>
          </div>
        </body>
      </html>
    </StateContext>
  )
}
